CREATE DATABASE Universidade;

USE Universidade;

CREATE TABLE IF NOT EXISTS Alunos (
  MAT int AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(50) NOT NULL,
  endereco VARCHAR(50) NOT NULL,
  cidade VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS Disciplinas (
COD_DISC int AUTO_INCREMENT PRIMARY KEY,
nome_disc VARCHAR(50) NOT NULL,
carga_hor int NOT NULL
);

CREATE TABLE IF NOT EXISTS Professores (
COD_PROF int AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(50) NOT NULL,
endereco VARCHAR(50) NOT NULL,
cidade VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS Turma (
COD_DISC int AUTO_INCREMENT PRIMARY KEY,
COD_TURMA int NOT NULL,
COD_PROF int NOT NULL,
ANO int NOT NULL,
horario VARCHAR(30) NOT NULL
);

SHOW TABLES;