CREATE DATABASE saida_vendas;
USE saida_vendas;
CREATE TABLE vendas(
ID_NF INT NOT NULL,
ID_ITEM INT NOT NULL,
COD_PROD INT NOT NULL,
VALOR_UNIT REAL NOT NULL,
QUANTIDADE INT NOT NULL,
DESCONTO INT,
PRIMARY KEY(ID_NF)
);

